### ISSUE TITLE
Decide what ORM to bundle with

### ISSUE THREAD

**Issue by killswitch** [kratos/kratos#8]
Have been looking at a few ORM's and need to make a decision on what what should be bundled with the framework.

**Comment by drknow42** [comment]
What are the few you've been looking at? As it stands the three that come to mind are MongooseJS, Sequelize, and Bookshelf.

**Comment by killswitch** [comment]
Mongoose is out as it's strictly MongoDB, I'd prefer to have a ORM that handles as many possible database types. So I'm looking at [Sequelize](http://docs.sequelizejs.com/en/latest/), [Bookshelf](http://bookshelfjs.org/), and [Waterline](https://github.com/balderdashy/waterline)

**Comment by cthecheese** [comment]
I definitely would pick up Waterline if there was an easy way to determine what database will be used during install like `kratos create myapp --pg` or something similar, the only issue I can see is that most of the useful Waterline adapters are community adapters. I feel like the loss of SQLite by going with Waterline and not Sequelize or Bookshelf is acceptable.

**Comment by killswitch** [comment]
Yeah right now Waterline has the most adapters, so I am leaning more towards that. Configuration Loader will autoload config into the database using the `database.js` config object. So you can define what adapter and connection details in there.

**Comment by killswitch** [comment]
Used Bookshelf.
